# Generated by Django 5.0.4 on 2024-05-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='college_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
