# Generated by Django 5.0.4 on 2024-06-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_model_college_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_model',
            old_name='college_id',
            new_name='course',
        ),
    ]
