# Generated by Django 5.0.4 on 2024-06-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_model_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_model',
            name='alternate_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
