# Generated by Django 5.0.4 on 2024-06-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_model_college_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.BooleanField(default=False)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_model')),
            ],
        ),
    ]
