# Generated by Django 5.0.4 on 2024-06-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_feedback',
            name='justify',
            field=models.CharField(max_length=4000),
        ),
    ]
