# Generated by Django 5.0.4 on 2024-06-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myClass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myclass',
            old_name='period_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='myclass',
            old_name='period_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='myclass',
            old_name='period_start',
            new_name='start',
        ),
    ]
